version: '3.9'
services:
 mongo:
  image: mongo:${MONGO_DB_VERSION}
  restart: always
  environment:
   MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USER}'
   MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
  ports:
   - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
  networks:
   - backend

networks:
 backend:
  name: backend-network
  driver: bridge
